
networks:
  lenic-network:

volumes:
  lenic-db-volume:
  lenic-log-volume:
  lenic-images-volume:

services:
  # App
  lenic:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    container_name: lenic-app
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    environment:
      APP_HOME:       ${APP_HOME}
      CFG_PATH:       ${CFG_PATH}
      HOST:           ${HOST}
      PORT:           ${PORT}
      DB_DSN:         postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=disable
      SESSION_SECRET: ${SESSION_SECRET}
      TOKEN_SECRET:   ${TOKEN_SECRET}
      IMG_PATH:       ${IMG_PATH}
      LOG_PATH:       ${LOG_PATH}
      MAIL_USER:      ${MAIL_USER}
      MAIL_PASS:      ${MAIL_PASS}
    ports:
      - "${PORT}:${PORT}"
    networks:
      - lenic-network
    volumes:
      - lenic-log-volume:/lenic/log
      - lenic-images-volume:/lenic/img
  # Migration Runner
  migrate:
    build:
      context: .
      dockerfile: docker/migrate.Dockerfile
    container_name: migrate
    depends_on:
      db:
        condition: service_healthy
    environment:
      APP_HOME: /opt/migrate_svc
      CFG_PATH: ${CFG_PATH}
      DB_DSN:   postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=disable
    networks:
      - lenic-network
  # DB
  db:
    image: postgres:16
    container_name: lenic-db
    environment:
      POSTGRES_USER:     ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB:       ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout:  5s
      retries:  10
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - lenic-network
    volumes:
      - lenic-db-volume:/var/lib/postgresql/data