
networks:
  lenic-network:

volumes:
  lenic-db-volume:

services:
  db:
    image: postgres:16
    container_name: lenic-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 2s
      timeout: 2s
      retries: 10
    ports:
      - "5432:5432"
    networks:
      - lenic-network
    volumes:
      - lenic-db-volume:/var/lib/postgresql/data

  migrate:
    build:
      context: .
      dockerfile: docker/migrate.Dockerfile
    container_name: lenic-migrate
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST_IN}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_TIMEOUT: ${DB_TIMEOUT}
    networks:
      - lenic-network
    volumes:
      - ./migrations:/migrations
      - ./scripts:/scripts
