config:
  server:
    read_timeout: 5 # seconds
    write_timeout: 10 # seconds
    shutdown_timeout: 15 # seconds
  session:
    session_duration: 24 # hours
  token:
    token_duration: 60 # minutes
  db:
    max_conns: 10
    max_idle_conns: 2
    max_conn_lifetime: 30 # minutes
    max_conn_idle_time: 5 # minutes
  img:
    originals_dir: "originals"
    previews_dir: "previews"
    preview_width: 200 # pixels
    preview_height: 200 # pixels
    jpeg_quality: 95
  logging:
    max_size: 10 # MB
    max_backups: 3
    max_age: 30 # days
    compress: true