server:
  read_timeout:     "5s"
  write_timeout:    "10s"
  shutdown_timeout: "15s"
session:
  duration: "24h"
token:
  duration: "60m"
db:
  max_conns:          10
  min_conns:          2
  max_conn_lifetime:  "10m"
  max_conn_idle_time: "5m"
img:
  img_dirs:
    originals: originals
    previews:  previews
  preview_dims:
    width:      200 # pixels
    height:     200 # pixels
  jpeg_quality: 95
log:
  max_size:    10 # MB
  max_age:     30
  max_backups: 3
  compress:    true
mail:
  host: smtp.gmail.com
  port: 587